functionsDirectory = "/Users/isaacpena/AG - shopping list app/netlify/functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/isaacpena/AG - shopping list app"
publishOrigin = "default"
commandOrigin = "config"
command = "npm install"
functions = "/Users/isaacpena/AG - shopping list app/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"