functionsDirectory = "/Users/isaacpena/AG - shopping list app/netlify/functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/isaacpena/AG - shopping list app"
publishOrigin = "default"
ignore = "git diff --quiet HEAD^ HEAD"
functions = "/Users/isaacpena/AG - shopping list app/netlify/functions"

[build.environment]
PYTHON_VERSION = "3.12"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]